"""add preregistered_beneficiaries and make patients.ci nullable

Revision ID: 20260719_000001
Revises: 675fe715e3bf
Create Date: 2026-07-19 00:00:01.000000
"""

from alembic import op
import sqlalchemy as sa


revision = "20260719_000001"
down_revision = "675fe715e3bf"
branch_labels = None
depends_on = None


# Padrón semilla de beneficiarios ya conocidos por la Fundación (pacientes.csv),
# usado para validar el autoregistro publico. Se excluyen entradas placeholder
# sin identidad real ("4 presos", "Luisito").
SEED_BENEFICIARIES = [
    {'nombres': 'Jaime', 'ap_paterno': 'Morales', 'ap_materno': 'Velasco', 'depto': 'Beni - Riberalta'},
    {'nombres': 'Maricruz', 'ap_paterno': 'Morales', 'ap_materno': 'Velasco', 'depto': 'Beni - Riberalta'},
    {'nombres': 'Medardo', 'ap_paterno': 'Morales', 'ap_materno': 'Velasco', 'depto': 'Beni - Riberalta'},
    {'nombres': 'Jessica Valeria', 'ap_paterno': 'Arteaga', 'ap_materno': 'Arza', 'depto': 'Beni - Trinidad'},
    {'nombres': 'Alejandra', 'ap_paterno': 'Barba', 'ap_materno': 'Jare', 'depto': 'Beni - Trinidad'},
    {'nombres': 'Vivian Teresa', 'ap_paterno': 'Bolling', 'ap_materno': 'Suarez', 'depto': 'Beni - Trinidad'},
    {'nombres': 'Sindy', 'ap_paterno': 'Castedo', 'ap_materno': 'Leigue', 'depto': 'Beni - Trinidad'},
    {'nombres': 'Daniel', 'ap_paterno': 'Dillen', 'ap_materno': 'Coca', 'depto': 'Beni - Trinidad'},
    {'nombres': 'Armelinda', 'ap_paterno': 'Flores', 'ap_materno': 'Oyola', 'depto': 'Beni - Trinidad'},
    {'nombres': 'Juana', 'ap_paterno': 'Guzman', 'ap_materno': 'Gutierrez', 'depto': 'Beni - Trinidad'},
    {'nombres': 'Alberto', 'ap_paterno': 'Jimenez', 'ap_materno': 'Coimbra', 'depto': 'Beni - Trinidad'},
    {'nombres': 'Maria Ely', 'ap_paterno': 'Jimenez', 'ap_materno': 'Mendoza', 'depto': 'Beni - Trinidad'},
    {'nombres': 'Mirián Arminda', 'ap_paterno': 'Jiménez', 'ap_materno': 'Mendoza', 'depto': 'Beni - Trinidad'},
    {'nombres': 'Miguel Enrique', 'ap_paterno': 'Melgar', 'ap_materno': 'Arteaga', 'depto': 'Beni - Trinidad'},
    {'nombres': 'Dennys', 'ap_paterno': 'Parrada', 'ap_materno': 'Villar', 'depto': 'Beni - Trinidad'},
    {'nombres': 'Yrene', 'ap_paterno': 'Paz', 'ap_materno': 'Teran', 'depto': 'Beni - Trinidad'},
    {'nombres': 'Justiniano', 'ap_paterno': 'Poiqui', 'ap_materno': None, 'depto': 'Beni - Trinidad'},
    {'nombres': 'Roberto', 'ap_paterno': 'Rea', 'ap_materno': 'Ruiz', 'depto': 'Beni - Trinidad'},
    {'nombres': 'Gueisa', 'ap_paterno': 'Roca', 'ap_materno': 'Ayala', 'depto': 'Beni - Trinidad'},
    {'nombres': 'Genesis', 'ap_paterno': 'Saavedra', 'ap_materno': 'Moruco', 'depto': 'Beni - Trinidad'},
    {'nombres': 'Gonzalo', 'ap_paterno': 'Soliz', 'ap_materno': 'Gauna', 'depto': 'Beni - Trinidad'},
    {'nombres': 'Jasmin', 'ap_paterno': 'Suarez', 'ap_materno': None, 'depto': 'Beni - Trinidad'},
    {'nombres': 'Ruth', 'ap_paterno': 'Tababary', 'ap_materno': 'Vda. De Campos', 'depto': 'Beni - Trinidad'},
    {'nombres': 'Wilge Luis', 'ap_paterno': 'Torrico', 'ap_materno': 'Calvi', 'depto': 'Beni - Trinidad'},
    {'nombres': 'Orlando', 'ap_paterno': 'Vargas', 'ap_materno': 'Ayala', 'depto': 'Beni - Trinidad'},
    {'nombres': 'Edgard Manuel', 'ap_paterno': 'Acapan', 'ap_materno': 'Mendez', 'depto': 'Cochabamba'},
    {'nombres': 'Jhaneth', 'ap_paterno': 'Alejo', 'ap_materno': 'Espejo', 'depto': 'Cochabamba'},
    {'nombres': 'Celia', 'ap_paterno': 'Almanza', 'ap_materno': 'Riveros', 'depto': 'Cochabamba'},
    {'nombres': 'Isabel Marth', 'ap_paterno': 'Andia', 'ap_materno': 'Ureña', 'depto': 'Cochabamba'},
    {'nombres': 'Jenny', 'ap_paterno': 'Angustia', 'ap_materno': 'Orozco', 'depto': 'Cochabamba'},
    {'nombres': 'Moises', 'ap_paterno': 'Apaza', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Delia', 'ap_paterno': 'Arnas', 'ap_materno': 'Vega', 'depto': 'Cochabamba'},
    {'nombres': 'Marcelo', 'ap_paterno': 'Arramayo', 'ap_materno': 'Padilla', 'depto': 'Cochabamba'},
    {'nombres': 'Sebastian', 'ap_paterno': 'Avila', 'ap_materno': 'Bascope', 'depto': 'Cochabamba'},
    {'nombres': 'Martin', 'ap_paterno': 'Bautista', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Margot', 'ap_paterno': 'Bellota', 'ap_materno': 'de Cossio', 'depto': 'Cochabamba'},
    {'nombres': 'Dora', 'ap_paterno': 'Caballero', 'ap_materno': 'Ledezma', 'depto': 'Cochabamba'},
    {'nombres': 'Vitalio', 'ap_paterno': 'Cabezas', 'ap_materno': 'Arroyo', 'depto': 'Cochabamba'},
    {'nombres': 'Ima', 'ap_paterno': 'Calle', 'ap_materno': 'Pocomari', 'depto': 'Cochabamba'},
    {'nombres': 'Basilia', 'ap_paterno': 'Camacho', 'ap_materno': 'Alvarez', 'depto': 'Cochabamba'},
    {'nombres': 'Jaime', 'ap_paterno': 'Camacho', 'ap_materno': 'Carrillo', 'depto': 'Cochabamba'},
    {'nombres': 'Maria Flora', 'ap_paterno': 'Camacho', 'ap_materno': 'Delgadillo', 'depto': 'Cochabamba'},
    {'nombres': 'Eduardo', 'ap_paterno': 'Camacho', 'ap_materno': 'Goita', 'depto': 'Cochabamba'},
    {'nombres': 'Anghelina Camila', 'ap_paterno': 'Campero', 'ap_materno': 'Alvarado', 'depto': 'Cochabamba'},
    {'nombres': 'Carlos Jose', 'ap_paterno': 'Canedon', 'ap_materno': 'V.', 'depto': 'Cochabamba'},
    {'nombres': 'Hilenia', 'ap_paterno': 'Canelas', 'ap_materno': 'Delgadillo', 'depto': 'Cochabamba'},
    {'nombres': 'Carmen', 'ap_paterno': 'Castellon', 'ap_materno': 'de Escalera', 'depto': 'Cochabamba'},
    {'nombres': 'Hilda', 'ap_paterno': 'Castro', 'ap_materno': 'Andia', 'depto': 'Cochabamba'},
    {'nombres': 'Florencia', 'ap_paterno': 'Chambi', 'ap_materno': 'Soliz', 'depto': 'Cochabamba'},
    {'nombres': 'Yolanda', 'ap_paterno': 'Chambi', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Tania', 'ap_paterno': 'Chavez', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Donato', 'ap_paterno': 'Choque', 'ap_materno': 'Vila', 'depto': 'Cochabamba'},
    {'nombres': 'Nancy', 'ap_paterno': 'Chumacero', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Nicolasa', 'ap_paterno': 'Colque', 'ap_materno': 'Mamani', 'depto': 'Cochabamba'},
    {'nombres': 'Maria Fernanda', 'ap_paterno': 'Conde', 'ap_materno': 'Cuba', 'depto': 'Cochabamba'},
    {'nombres': 'Margot', 'ap_paterno': 'Cortez', 'ap_materno': 'Cantuta', 'depto': 'Cochabamba'},
    {'nombres': 'Patricia', 'ap_paterno': 'Covarrubias', 'ap_materno': 'Beltran', 'depto': 'Cochabamba'},
    {'nombres': 'Miriam', 'ap_paterno': 'Cruz', 'ap_materno': 'Claros', 'depto': 'Cochabamba'},
    {'nombres': 'Dolores', 'ap_paterno': 'Cruz', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Evangelina', 'ap_paterno': 'Cuba', 'ap_materno': 'Aliaga', 'depto': 'Cochabamba'},
    {'nombres': 'Eivar', 'ap_paterno': 'Cusipuma', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Leonor Melvi', 'ap_paterno': 'Diaz', 'ap_materno': 'Quiroga', 'depto': 'Cochabamba'},
    {'nombres': 'Stephany Daniela', 'ap_paterno': 'Dipp', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Juan Carlos', 'ap_paterno': 'Emilio', 'ap_materno': 'Churqui', 'depto': 'Cochabamba'},
    {'nombres': 'Aretha Mariana', 'ap_paterno': 'Fernandez', 'ap_materno': 'Carrillo', 'depto': 'Cochabamba'},
    {'nombres': 'Maria Rosa', 'ap_paterno': 'Fernandez', 'ap_materno': 'Zelada', 'depto': 'Cochabamba'},
    {'nombres': 'Fortunato', 'ap_paterno': 'Flores', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Victor Hugo', 'ap_paterno': 'Flores', 'ap_materno': 'Rocha', 'depto': 'Cochabamba'},
    {'nombres': 'Jose Luis', 'ap_paterno': 'Foronda', 'ap_materno': 'Benavides', 'depto': 'Cochabamba'},
    {'nombres': 'Albina', 'ap_paterno': 'Garcia', 'ap_materno': 'Perez', 'depto': 'Cochabamba'},
    {'nombres': 'Basilia Braulia', 'ap_paterno': 'Gonzales', 'ap_materno': 'Huella', 'depto': 'Cochabamba'},
    {'nombres': 'Marcos Antonio', 'ap_paterno': 'Guzmán', 'ap_materno': 'Vargas', 'depto': 'Cochabamba'},
    {'nombres': 'Freddy', 'ap_paterno': 'Guzman', 'ap_materno': 'Zelada', 'depto': 'Cochabamba'},
    {'nombres': 'Albina', 'ap_paterno': 'Herbas', 'ap_materno': 'de Flores', 'depto': 'Cochabamba'},
    {'nombres': 'Agripina', 'ap_paterno': 'Heredia', 'ap_materno': 'Caballero', 'depto': 'Cochabamba'},
    {'nombres': 'Lenny', 'ap_paterno': 'Hinojosa', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Drynna Belen', 'ap_paterno': 'Hinojosa', 'ap_materno': 'Triveño', 'depto': 'Cochabamba'},
    {'nombres': 'Feliciano', 'ap_paterno': 'Jaimes', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Ernesto', 'ap_paterno': 'Jimenez', 'ap_materno': 'Perez', 'depto': 'Cochabamba'},
    {'nombres': 'Rosa', 'ap_paterno': 'La Fuente', 'ap_materno': 'Fernandez', 'depto': 'Cochabamba'},
    {'nombres': 'Jorge Wilder', 'ap_paterno': 'Lazarte', 'ap_materno': 'Rodriguez', 'depto': 'Cochabamba'},
    {'nombres': 'Wilfredo', 'ap_paterno': 'Ledezma', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Alex', 'ap_paterno': 'Lenin', 'ap_materno': 'Morato', 'depto': 'Cochabamba'},
    {'nombres': 'Adbias', 'ap_paterno': 'Leon', 'ap_materno': 'Zapata', 'depto': 'Cochabamba'},
    {'nombres': 'Enrique', 'ap_paterno': 'Lique', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Fidelia', 'ap_paterno': 'Lopez', 'ap_materno': 'Camacho', 'depto': 'Cochabamba'},
    {'nombres': 'Antonia', 'ap_paterno': 'Lucano', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Consuelo', 'ap_paterno': 'Lujan', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Angel Emanuel', 'ap_paterno': 'Maire', 'ap_materno': 'Pastor', 'depto': 'Cochabamba'},
    {'nombres': 'Cintia Roxana', 'ap_paterno': 'Mamani', 'ap_materno': 'Aguilera', 'depto': 'Cochabamba'},
    {'nombres': 'Miguel', 'ap_paterno': 'Mamani', 'ap_materno': 'Fernandez', 'depto': 'Cochabamba'},
    {'nombres': 'Estefania', 'ap_paterno': 'Mamani', 'ap_materno': 'Usnayo', 'depto': 'Cochabamba'},
    {'nombres': 'Lucia', 'ap_paterno': 'Mariscal', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Adrian', 'ap_paterno': 'Medrano', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Brandon', 'ap_paterno': 'Medrano', 'ap_materno': 'Cadima', 'depto': 'Cochabamba'},
    {'nombres': 'Clelia', 'ap_paterno': 'Medrano', 'ap_materno': 'Fuentes', 'depto': 'Cochabamba'},
    {'nombres': 'Dario', 'ap_paterno': 'Mejia', 'ap_materno': 'Navia', 'depto': 'Cochabamba'},
    {'nombres': 'Beatriz', 'ap_paterno': 'Mejia', 'ap_materno': 'R.', 'depto': 'Cochabamba'},
    {'nombres': 'Marco A.', 'ap_paterno': 'Mejia', 'ap_materno': 'Rivera', 'depto': 'Cochabamba'},
    {'nombres': 'Maria Ceñida', 'ap_paterno': 'Meneses', 'ap_materno': 'Veizaga', 'depto': 'Cochabamba'},
    {'nombres': 'Orlando', 'ap_paterno': 'Montaño', 'ap_materno': 'Ledezma', 'depto': 'Cochabamba'},
    {'nombres': 'Rodrigo Richard', 'ap_paterno': 'Morato', 'ap_materno': 'Salinas', 'depto': 'Cochabamba'},
    {'nombres': 'Ricarda', 'ap_paterno': 'Muñoz', 'ap_materno': 'de Rosas', 'depto': 'Cochabamba'},
    {'nombres': 'Antony Abraham', 'ap_paterno': 'Muñoz', 'ap_materno': 'Peñaloza', 'depto': 'Cochabamba'},
    {'nombres': 'Angel Alberto', 'ap_paterno': 'Muñoz', 'ap_materno': 'Pereyra', 'depto': 'Cochabamba'},
    {'nombres': 'Alejandro', 'ap_paterno': 'Navarro', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Isidora', 'ap_paterno': 'Navarro', 'ap_materno': 'Copa', 'depto': 'Cochabamba'},
    {'nombres': 'Margarita', 'ap_paterno': 'Negrete', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Silvetti', 'ap_paterno': 'Nereo', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Petrona', 'ap_paterno': 'Nogales', 'ap_materno': 'De Hinojosa', 'depto': 'Cochabamba'},
    {'nombres': 'Rodrigo', 'ap_paterno': 'Nogales', 'ap_materno': 'Rivera', 'depto': 'Cochabamba'},
    {'nombres': 'Jaime', 'ap_paterno': 'Olmos', 'ap_materno': 'Olivares', 'depto': 'Cochabamba'},
    {'nombres': 'Mery', 'ap_paterno': 'Oropeza', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Wilson', 'ap_paterno': 'Oropeza', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Jenny', 'ap_paterno': 'Orozco', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Jose', 'ap_paterno': 'Ortiz', 'ap_materno': 'Camacho', 'depto': 'Cochabamba'},
    {'nombres': 'Peregrino', 'ap_paterno': 'Padilla', 'ap_materno': 'Villalobos', 'depto': 'Cochabamba'},
    {'nombres': 'Laida', 'ap_paterno': 'Palavicino', 'ap_materno': 'Herbas', 'depto': 'Cochabamba'},
    {'nombres': 'Erick Juvenal', 'ap_paterno': 'Pancorbo', 'ap_materno': 'Guzman', 'depto': 'Cochabamba'},
    {'nombres': 'Martha', 'ap_paterno': 'Pardo', 'ap_materno': 'Delgadillo de Vargas', 'depto': 'Cochabamba'},
    {'nombres': 'Eduardo', 'ap_paterno': 'Peñaranda', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'E. Geary', 'ap_paterno': 'Perez', 'ap_materno': 'Claros', 'depto': 'Cochabamba'},
    {'nombres': 'Cristina', 'ap_paterno': 'Perez', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Rosa Benigna', 'ap_paterno': 'Perez', 'ap_materno': 'Valenzuela', 'depto': 'Cochabamba'},
    {'nombres': 'Javier', 'ap_paterno': 'Pol', 'ap_materno': 'Aramayo', 'depto': 'Cochabamba'},
    {'nombres': 'Nely', 'ap_paterno': 'Quinteros', 'ap_materno': 'Terrazas', 'depto': 'Cochabamba'},
    {'nombres': 'Lidia', 'ap_paterno': 'Quiroz', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Patricia', 'ap_paterno': 'Ramirez', 'ap_materno': 'Herbas', 'depto': 'Cochabamba'},
    {'nombres': 'Julia', 'ap_paterno': 'Ramos', 'ap_materno': 'Kanata', 'depto': 'Cochabamba'},
    {'nombres': 'Mauricio', 'ap_paterno': 'Rivas', 'ap_materno': 'Cardona', 'depto': 'Cochabamba'},
    {'nombres': 'Juan Jose', 'ap_paterno': 'Rodriguez', 'ap_materno': 'Garcia', 'depto': 'Cochabamba'},
    {'nombres': 'Jose Hugo', 'ap_paterno': 'Rodriguez', 'ap_materno': 'Lopez', 'depto': 'Cochabamba'},
    {'nombres': 'Maria Eugenia', 'ap_paterno': 'Rojas', 'ap_materno': 'Maria', 'depto': 'Cochabamba'},
    {'nombres': 'Dunia', 'ap_paterno': 'Rojas', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Vanesa Rosalia', 'ap_paterno': 'Rojas', 'ap_materno': 'Paredes', 'depto': 'Cochabamba'},
    {'nombres': 'Ruth Natalia', 'ap_paterno': 'Rolon', 'ap_materno': 'Gamarra', 'depto': 'Cochabamba'},
    {'nombres': 'Wilmer', 'ap_paterno': 'Roman', 'ap_materno': 'Torrico', 'depto': 'Cochabamba'},
    {'nombres': 'Juana Evangelina', 'ap_paterno': 'Romero', 'ap_materno': 'Ledezma', 'depto': 'Cochabamba'},
    {'nombres': 'Ruth Marlene', 'ap_paterno': 'Roque', 'ap_materno': 'Guzmán', 'depto': 'Cochabamba'},
    {'nombres': 'Ruddy', 'ap_paterno': 'Salazar', 'ap_materno': 'Caero', 'depto': 'Cochabamba'},
    {'nombres': 'Angel Andres', 'ap_paterno': 'Salvatierra', 'ap_materno': 'Cabrero', 'depto': 'Cochabamba'},
    {'nombres': 'Juan Carlos', 'ap_paterno': 'Salvatierra', 'ap_materno': 'Sejas', 'depto': 'Cochabamba'},
    {'nombres': 'Doris', 'ap_paterno': 'Sanchez', 'ap_materno': 'Moreno', 'depto': 'Cochabamba'},
    {'nombres': 'Sixto', 'ap_paterno': 'Sandoval', 'ap_materno': 'Fuentes', 'depto': 'Cochabamba'},
    {'nombres': 'José Alejandro', 'ap_paterno': 'Sandoval', 'ap_materno': 'Siles', 'depto': 'Cochabamba'},
    {'nombres': 'Lenny Sandra', 'ap_paterno': 'Sandoval', 'ap_materno': 'Siles', 'depto': 'Cochabamba'},
    {'nombres': 'Domitila', 'ap_paterno': 'Sarmiento', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Julio Cesar', 'ap_paterno': 'Sejas', 'ap_materno': 'Teran', 'depto': 'Cochabamba'},
    {'nombres': 'Elena', 'ap_paterno': 'Siles', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Iveth David', 'ap_paterno': 'Soto', 'ap_materno': 'Valdez', 'depto': 'Cochabamba'},
    {'nombres': 'Maria Inez', 'ap_paterno': 'Terrazas', 'ap_materno': 'Camacho', 'depto': 'Cochabamba'},
    {'nombres': 'Maria Luz', 'ap_paterno': 'Terrazas', 'ap_materno': 'Mamani', 'depto': 'Cochabamba'},
    {'nombres': 'Carmen', 'ap_paterno': 'Thames', 'ap_materno': 'Velasquez', 'depto': 'Cochabamba'},
    {'nombres': 'Aldo German', 'ap_paterno': 'Tordoya', 'ap_materno': 'Ibañez', 'depto': 'Cochabamba'},
    {'nombres': 'Nancy Aurora', 'ap_paterno': 'Torrico', 'ap_materno': 'Zambrana', 'depto': 'Cochabamba'},
    {'nombres': 'Enrique Javier', 'ap_paterno': 'Tribeño', 'ap_materno': 'Ortiz', 'depto': 'Cochabamba'},
    {'nombres': 'Nomberto', 'ap_paterno': 'Triveño', 'ap_materno': 'Navia', 'depto': 'Cochabamba'},
    {'nombres': 'Silvia', 'ap_paterno': 'Ugalde', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Edgar Ernesto', 'ap_paterno': 'Ugarte', 'ap_materno': 'Balanza', 'depto': 'Cochabamba'},
    {'nombres': 'Analia Ester', 'ap_paterno': 'Vallejo', 'ap_materno': 'Moya', 'depto': 'Cochabamba'},
    {'nombres': 'Miguel Angel', 'ap_paterno': 'Valverde', 'ap_materno': 'Murillo', 'depto': 'Cochabamba'},
    {'nombres': 'Marco Antonio', 'ap_paterno': 'Vasquez', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Salome', 'ap_paterno': 'Vega', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Alejandrina', 'ap_paterno': 'Veizaga', 'ap_materno': 'Montecinos', 'depto': 'Cochabamba'},
    {'nombres': 'Mariela', 'ap_paterno': 'Velasquez', 'ap_materno': 'Rojas', 'depto': 'Cochabamba'},
    {'nombres': 'Olga', 'ap_paterno': 'Velazquez', 'ap_materno': 'Arias', 'depto': 'Cochabamba'},
    {'nombres': 'Angel', 'ap_paterno': 'Ventura', 'ap_materno': 'Flores', 'depto': 'Cochabamba'},
    {'nombres': 'Chanel', 'ap_paterno': 'Vera', 'ap_materno': 'Caceres', 'depto': 'Cochabamba'},
    {'nombres': 'Florencia', 'ap_paterno': 'Vergara', 'ap_materno': 'Terán Flores', 'depto': 'Cochabamba'},
    {'nombres': 'Jorge Enrique', 'ap_paterno': 'Villamor', 'ap_materno': 'Loras', 'depto': 'Cochabamba'},
    {'nombres': 'Samantha Emma', 'ap_paterno': 'Villanueva', 'ap_materno': 'Quiroga', 'depto': 'Cochabamba'},
    {'nombres': 'Macario', 'ap_paterno': 'Villaroel', 'ap_materno': 'Claros', 'depto': 'Cochabamba'},
    {'nombres': 'Eusebia', 'ap_paterno': 'Zelada', 'ap_materno': None, 'depto': 'Cochabamba'},
    {'nombres': 'Juan Carlos', 'ap_paterno': 'Zelada', 'ap_materno': 'Quinteros', 'depto': 'Cochabamba'},
    {'nombres': 'Esteban', 'ap_paterno': 'Zurita', 'ap_materno': 'Herrera', 'depto': 'Cochabamba'},
    {'nombres': 'Analia', 'ap_paterno': 'Zurita', 'ap_materno': 'Medrano', 'depto': 'Cochabamba'},
    {'nombres': 'Giovana', 'ap_paterno': 'Zurita', 'ap_materno': 'Meruvia', 'depto': 'Cochabamba'},
    {'nombres': 'C. Cecilia', 'ap_paterno': 'Alba', 'ap_materno': 'Pieracci', 'depto': 'La Paz'},
    {'nombres': 'Marienela Casta Madelen', 'ap_paterno': 'Alcázar', 'ap_materno': 'Cullen', 'depto': 'La Paz'},
    {'nombres': 'Jose Diego', 'ap_paterno': 'Ardaya', 'ap_materno': 'Escandino', 'depto': 'La Paz'},
    {'nombres': 'Ana Carola', 'ap_paterno': 'Arias', 'ap_materno': 'Pacheco', 'depto': 'La Paz'},
    {'nombres': 'David', 'ap_paterno': 'Ayala', 'ap_materno': 'Quispe', 'depto': 'La Paz'},
    {'nombres': 'Soraya', 'ap_paterno': 'Caceres', 'ap_materno': None, 'depto': 'La Paz'},
    {'nombres': 'Patricia', 'ap_paterno': 'Calvimontes', 'ap_materno': 'Cossio', 'depto': 'La Paz'},
    {'nombres': 'Gabriela Josefa', 'ap_paterno': 'Choque', 'ap_materno': 'Zabaleta', 'depto': 'La Paz'},
    {'nombres': 'Elijah Antonio', 'ap_paterno': 'España', 'ap_materno': 'Paredes', 'depto': 'La Paz'},
    {'nombres': 'Alba Minerva', 'ap_paterno': 'Flores', 'ap_materno': 'Choque', 'depto': 'La Paz'},
    {'nombres': 'Leonor Luwinka', 'ap_paterno': 'Flores', 'ap_materno': 'Choque', 'depto': 'La Paz'},
    {'nombres': 'Lucia Nancy', 'ap_paterno': 'Gutierrez', 'ap_materno': None, 'depto': 'La Paz'},
    {'nombres': 'Mary Laura', 'ap_paterno': 'Leon', 'ap_materno': 'Tinta', 'depto': 'La Paz'},
    {'nombres': 'Selim', 'ap_paterno': 'Londoño', 'ap_materno': 'Guarachi', 'depto': 'La Paz'},
    {'nombres': 'Claudia Olivia', 'ap_paterno': 'López', 'ap_materno': 'Zubieta', 'depto': 'La Paz'},
    {'nombres': 'Vivian', 'ap_paterno': 'López', 'ap_materno': 'Zubieta', 'depto': 'La Paz'},
    {'nombres': 'Juan Francisco', 'ap_paterno': 'Luna', 'ap_materno': None, 'depto': 'La Paz'},
    {'nombres': 'Ivan Mauricio', 'ap_paterno': 'Martinez', 'ap_materno': 'Leon', 'depto': 'La Paz'},
    {'nombres': 'Luna Isabel', 'ap_paterno': 'Molina', 'ap_materno': 'Calvimontes', 'depto': 'La Paz'},
    {'nombres': 'Sergio', 'ap_paterno': 'Salinas', 'ap_materno': 'Arevalo', 'depto': 'La Paz'},
    {'nombres': 'Virginia', 'ap_paterno': 'Vasquez', 'ap_materno': 'Siles', 'depto': 'La Paz'},
    {'nombres': 'Elena Victoria', 'ap_paterno': 'Yujra', 'ap_materno': 'Lagos', 'depto': 'La Paz'},
    {'nombres': 'Fabian Roamir', 'ap_paterno': 'Gutierrez', 'ap_materno': 'Choque', 'depto': 'Oruro'},
    {'nombres': 'Jesica', 'ap_paterno': 'Ibarra', 'ap_materno': None, 'depto': 'Oruro'},
    {'nombres': 'Atenea Bertha', 'ap_paterno': 'Pardo', 'ap_materno': 'Chirinos', 'depto': 'Oruro'},
    {'nombres': 'Daniela', 'ap_paterno': 'Torrez', 'ap_materno': None, 'depto': 'Oruro'},
    {'nombres': 'Ingird Vaneza', 'ap_paterno': 'Valencia', 'ap_materno': 'Rada', 'depto': 'Oruro'},
    {'nombres': 'Cristian', 'ap_paterno': 'Chimo', 'ap_materno': 'Quispe', 'depto': 'Potosí'},
    {'nombres': 'Gabriel Florencio', 'ap_paterno': 'Mamani', 'ap_materno': 'Gutiérrez', 'depto': 'Potosí'},
    {'nombres': 'Emanuel Iver', 'ap_paterno': 'Mamanii', 'ap_materno': 'Pardo', 'depto': 'Potosí'},
    {'nombres': 'Guisela', 'ap_paterno': 'Murillo', 'ap_materno': None, 'depto': 'Potosí'},
    {'nombres': 'Cecilia', 'ap_paterno': 'Alarcon', 'ap_materno': None, 'depto': 'Santa Cruz'},
    {'nombres': 'Kamila Laisney', 'ap_paterno': 'Alvarado', 'ap_materno': 'Inozoa', 'depto': 'Santa Cruz'},
    {'nombres': 'Mateo', 'ap_paterno': 'Asin', 'ap_materno': 'A.', 'depto': 'Santa Cruz'},
    {'nombres': 'Leonardo', 'ap_paterno': 'Balcazar', 'ap_materno': 'Hurtado', 'depto': 'Santa Cruz'},
    {'nombres': 'Alcides', 'ap_paterno': 'Baqueiros', 'ap_materno': 'Cuellar', 'depto': 'Santa Cruz'},
    {'nombres': 'Mathias Fabrizio', 'ap_paterno': 'Bowles', 'ap_materno': 'Rojas', 'depto': 'Santa Cruz'},
    {'nombres': 'Fabio Cesar', 'ap_paterno': 'Carrasco', 'ap_materno': 'Machaca', 'depto': 'Santa Cruz'},
    {'nombres': 'Luis Alejandro', 'ap_paterno': 'Castro', 'ap_materno': 'Carrasco', 'depto': 'Santa Cruz'},
    {'nombres': 'Michael Alexander', 'ap_paterno': 'Chanavi', 'ap_materno': 'Cesari', 'depto': 'Santa Cruz'},
    {'nombres': 'Daniela', 'ap_paterno': 'Cortez', 'ap_materno': 'Perez', 'depto': 'Santa Cruz'},
    {'nombres': 'Erick Ruffo', 'ap_paterno': 'Cossio', 'ap_materno': 'Aguilar', 'depto': 'Santa Cruz'},
    {'nombres': 'Jaime', 'ap_paterno': 'Dominguez', 'ap_materno': 'Tanaka', 'depto': 'Santa Cruz'},
    {'nombres': 'Raul', 'ap_paterno': 'Duran', 'ap_materno': 'Lopez', 'depto': 'Santa Cruz'},
    {'nombres': 'Daniel', 'ap_paterno': 'Eguez', 'ap_materno': 'Arauz', 'depto': 'Santa Cruz'},
    {'nombres': 'Ruben Eduardo', 'ap_paterno': 'Figueroa', 'ap_materno': 'Rea', 'depto': 'Santa Cruz'},
    {'nombres': 'Carlos Joaquin', 'ap_paterno': 'Flores', 'ap_materno': 'Chavez', 'depto': 'Santa Cruz'},
    {'nombres': 'Alan Oscar', 'ap_paterno': 'Garcia', 'ap_materno': 'Añez', 'depto': 'Santa Cruz'},
    {'nombres': 'Luka Alessandro', 'ap_paterno': 'Garcia', 'ap_materno': 'Gabriel', 'depto': 'Santa Cruz'},
    {'nombres': 'Ashly', 'ap_paterno': 'Garcia', 'ap_materno': 'Garcia', 'depto': 'Santa Cruz'},
    {'nombres': 'Pedro Miguel', 'ap_paterno': 'Gonzales', 'ap_materno': 'Pedro', 'depto': 'Santa Cruz'},
    {'nombres': 'Saul', 'ap_paterno': 'Herbas', 'ap_materno': None, 'depto': 'Santa Cruz'},
    {'nombres': 'Alex Yamir', 'ap_paterno': 'Hurtado', 'ap_materno': 'Calderon', 'depto': 'Santa Cruz'},
    {'nombres': 'Maria Fernanda', 'ap_paterno': 'Ibañez', 'ap_materno': 'Barriga', 'depto': 'Santa Cruz'},
    {'nombres': 'Genesis Daniela', 'ap_paterno': 'Jauregui', 'ap_materno': 'Pedraza', 'depto': 'Santa Cruz'},
    {'nombres': 'Naomi Victoria', 'ap_paterno': 'Linares', 'ap_materno': 'Nava', 'depto': 'Santa Cruz'},
    {'nombres': 'Jorge Fernando', 'ap_paterno': 'Lopez', 'ap_materno': 'Hurtado', 'depto': 'Santa Cruz'},
    {'nombres': 'Gabriel', 'ap_paterno': 'Martinez', 'ap_materno': 'Lema', 'depto': 'Santa Cruz'},
    {'nombres': 'Jimena', 'ap_paterno': 'Medrano', 'ap_materno': 'Arispe', 'depto': 'Santa Cruz'},
    {'nombres': 'Melissa', 'ap_paterno': 'Miranda', 'ap_materno': 'Galarza', 'depto': 'Santa Cruz'},
    {'nombres': 'Andrea Faviana', 'ap_paterno': 'Molina', 'ap_materno': 'Rivera', 'depto': 'Santa Cruz'},
    {'nombres': 'Ramiro Antonio', 'ap_paterno': 'Ortuño', 'ap_materno': 'Echavarria', 'depto': 'Santa Cruz'},
    {'nombres': 'Carla Stephanie', 'ap_paterno': 'Osinaga', 'ap_materno': 'Montero', 'depto': 'Santa Cruz'},
    {'nombres': 'Katsumi', 'ap_paterno': 'Penazzi', 'ap_materno': 'Shiroma', 'depto': 'Santa Cruz'},
    {'nombres': 'Demmy Jhair', 'ap_paterno': 'Pereyra', 'ap_materno': 'Carballo', 'depto': 'Santa Cruz'},
    {'nombres': 'Carla Yesika', 'ap_paterno': 'Quiroga', 'ap_materno': 'Soliz', 'depto': 'Santa Cruz'},
    {'nombres': 'Kevin Steven', 'ap_paterno': 'Rengel', 'ap_materno': 'Miche', 'depto': 'Santa Cruz'},
    {'nombres': 'Maria Betania', 'ap_paterno': 'Ribera', 'ap_materno': None, 'depto': 'Santa Cruz'},
    {'nombres': 'Sebastian', 'ap_paterno': 'Rossell', 'ap_materno': 'Ribera', 'depto': 'Santa Cruz'},
    {'nombres': 'Ramon Gabriel', 'ap_paterno': 'Rueda', 'ap_materno': 'Ramon', 'depto': 'Santa Cruz'},
    {'nombres': 'Lourdes Michelle', 'ap_paterno': 'Saavedra', 'ap_materno': 'Justiniano', 'depto': 'Santa Cruz'},
    {'nombres': 'Jade Rafaella', 'ap_paterno': 'Sanabria', 'ap_materno': 'Cespedes', 'depto': 'Santa Cruz'},
    {'nombres': 'Carlos David', 'ap_paterno': 'Saucedo', 'ap_materno': 'Soto', 'depto': 'Santa Cruz'},
    {'nombres': 'Yanahi Fernanda', 'ap_paterno': 'Severiche', 'ap_materno': 'Rojas', 'depto': 'Santa Cruz'},
    {'nombres': 'Jhonny', 'ap_paterno': 'Siles', 'ap_materno': None, 'depto': 'Santa Cruz'},
    {'nombres': 'Nicolas', 'ap_paterno': 'Subirona', 'ap_materno': 'Herrera', 'depto': 'Santa Cruz'},
    {'nombres': 'Valesska', 'ap_paterno': 'Subirona', 'ap_materno': 'Herrera', 'depto': 'Santa Cruz'},
    {'nombres': 'Maria Joaquina', 'ap_paterno': 'Uriona', 'ap_materno': 'Moreno', 'depto': 'Santa Cruz'},
    {'nombres': 'Uzbeth', 'ap_paterno': 'Vaca', 'ap_materno': 'Borja', 'depto': 'Santa Cruz'},
    {'nombres': 'Laura Dayana', 'ap_paterno': 'Vega', 'ap_materno': 'Arteaga', 'depto': 'Santa Cruz'},
    {'nombres': 'Guadalupe', 'ap_paterno': 'Vega', 'ap_materno': 'Pinto', 'depto': 'Santa Cruz'},
    {'nombres': 'Oscar Rafael', 'ap_paterno': 'Zabala', 'ap_materno': 'Giles', 'depto': 'Santa Cruz'},
    {'nombres': 'Nancy Berta', 'ap_paterno': 'Zegarra', 'ap_materno': 'Vda. De Chavez', 'depto': 'Santa Cruz'},
    {'nombres': 'Carla', 'ap_paterno': 'Zuñiga', 'ap_materno': 'Méndez', 'depto': 'Santa Cruz'},
    {'nombres': 'Servando', 'ap_paterno': 'calderon', 'ap_materno': None, 'depto': 'Santa Cruz'},
    {'nombres': 'Noelia', 'ap_paterno': 'Bernal', 'ap_materno': 'Aceytuno', 'depto': 'Sucre'},
    {'nombres': 'Maria Lidoska', 'ap_paterno': 'Careaga', 'ap_materno': 'Roncal', 'depto': 'Sucre'},
    {'nombres': 'Adrian Camilo', 'ap_paterno': 'Martinez', 'ap_materno': 'Telles', 'depto': 'Sucre'},
    {'nombres': 'Facundo Joaquin', 'ap_paterno': 'Sapiense', 'ap_materno': 'Lema', 'depto': 'Sucre'},
    {'nombres': 'James Franco', 'ap_paterno': 'Vasques', 'ap_materno': 'Cueto', 'depto': 'Sucre'},
    {'nombres': 'Adriana', 'ap_paterno': 'Arduz', 'ap_materno': 'Mendieta', 'depto': 'Tarija'},
    {'nombres': 'Pablo', 'ap_paterno': 'Arduz', 'ap_materno': 'Mendieta', 'depto': 'Tarija'},
    {'nombres': 'Gonzalo', 'ap_paterno': 'Cabezas', 'ap_materno': None, 'depto': 'Tarija'},
    {'nombres': 'José Felix', 'ap_paterno': 'Camponovo', 'ap_materno': 'Ulloa', 'depto': 'Tarija'},
    {'nombres': 'Liliana', 'ap_paterno': 'Castrillo', 'ap_materno': None, 'depto': 'Tarija'},
    {'nombres': 'Victoria Camila', 'ap_paterno': 'Chavarria', 'ap_materno': 'Guerrero', 'depto': 'Tarija'},
    {'nombres': 'Susana', 'ap_paterno': 'Copali', 'ap_materno': 'Negrete', 'depto': 'Tarija'},
    {'nombres': 'Guadalupe Ivis', 'ap_paterno': 'Huanca', 'ap_materno': 'Gaspar', 'depto': 'Tarija'},
    {'nombres': 'Olga', 'ap_paterno': 'León', 'ap_materno': None, 'depto': 'Tarija'},
    {'nombres': 'Pilar', 'ap_paterno': 'Martinez', 'ap_materno': 'de Jaramillo', 'depto': 'Tarija'},
    {'nombres': 'Juan Daniel', 'ap_paterno': 'Molina', 'ap_materno': 'Rivera', 'depto': 'Tarija'},
    {'nombres': 'Nancy', 'ap_paterno': 'Montes', 'ap_materno': 'de Oca', 'depto': 'Tarija'},
    {'nombres': 'Camila', 'ap_paterno': 'Moreno', 'ap_materno': 'Huerta', 'depto': 'Tarija'},
    {'nombres': 'Maria Rosa', 'ap_paterno': 'Raña', 'ap_materno': 'Gaite', 'depto': 'Tarija'},
    {'nombres': 'Roberto Marcelo', 'ap_paterno': 'Rotunno', 'ap_materno': 'Serrupo', 'depto': 'Tarija'},
    {'nombres': 'Miguel Angel', 'ap_paterno': 'Suárez', 'ap_materno': 'Rivera', 'depto': 'Tarija'},
    {'nombres': 'Aron Israel', 'ap_paterno': 'Velasques', 'ap_materno': 'Chavez', 'depto': 'Tarija'},
    {'nombres': 'Pedro Miguel', 'ap_paterno': 'Velasquez', 'ap_materno': 'Velasquez', 'depto': 'Tarija'},
    {'nombres': 'Elffy Bass', 'ap_paterno': 'Werner', 'ap_materno': 'Antunez', 'depto': 'Tarija'},
    {'nombres': 'norberto', 'ap_paterno': 'Zenteno', 'ap_materno': 'Ortega', 'depto': 'Tarija'},
]


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    patient_columns = {col["name"]: col for col in inspector.get_columns("patients")}
    if patient_columns.get("ci", {}).get("nullable") is False:
        op.alter_column("patients", "ci", existing_type=sa.String(length=32), nullable=True)

    if "preregistered_beneficiaries" not in inspector.get_table_names():
        preregistered_table = op.create_table(
            "preregistered_beneficiaries",
            sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
            sa.Column("nombres", sa.String(length=120), nullable=False),
            sa.Column("ap_paterno", sa.String(length=80), nullable=True),
            sa.Column("ap_materno", sa.String(length=80), nullable=True),
            sa.Column("depto", sa.String(length=80), nullable=True),
            sa.Column("matched_patient_id", sa.BigInteger(), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
            sa.ForeignKeyConstraint(["matched_patient_id"], ["patients.id"], ondelete="SET NULL"),
        )
        op.bulk_insert(preregistered_table, SEED_BENEFICIARIES)


def downgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if "preregistered_beneficiaries" in inspector.get_table_names():
        op.drop_table("preregistered_beneficiaries")

    patient_columns = {col["name"]: col for col in inspector.get_columns("patients")}
    if patient_columns.get("ci", {}).get("nullable") is True:
        op.alter_column("patients", "ci", existing_type=sa.String(length=32), nullable=False)
