"""simplificar_tabla_treatments

Revision ID: 2d83fa471857
Revises: 20260212_000002
Create Date: 2026-02-22 22:46:40.693774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d83fa471857'
down_revision = '20260212_000002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voluntary_pledges')
    op.add_column('patient_treatments', sa.Column('dosis_diaria', sa.Float(), nullable=True))
    op.drop_column('patient_treatments', 'tipo')
    op.drop_column('patient_treatments', 'dosis_manana')
    op.drop_column('patient_treatments', 'dosis_noche')
    op.drop_column('patient_treatments', 'dosis_tarde')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_treatments', sa.Column('dosis_tarde', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('patient_treatments', sa.Column('dosis_noche', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('patient_treatments', sa.Column('dosis_manana', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('patient_treatments', sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('patient_treatments', 'dosis_diaria')
    op.create_table('voluntary_pledges',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('monto_compromiso', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('fecha_firma', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('url_pdf', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('vigente', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('monto_compromiso >= 50::numeric', name='ck_pledge_min_amount'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='voluntary_pledges_patient_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='voluntary_pledges_pkey'),
    sa.UniqueConstraint('patient_id', 'vigente', name='uq_pledge_patient_vigente')
    )
    # ### end Alembic commands ###