"""remove_unique_constraint_tutor_ci

Revision ID: 53ee1a88532d
Revises: 871c945710ae
Create Date: 2026-04-28 09:23:19.324459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ee1a88532d'
down_revision = '871c945710ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tutors_ci_key', 'tutors', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tutors_ci_key', 'tutors', ['ci'])
    # ### end Alembic commands ###