"""Refactor director_insulin_deliveries

Revision ID: 675fe715e3bf
Revises: 946305953d83
Create Date: 2026-06-12 21:49:21.409164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675fe715e3bf'
down_revision = '946305953d83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('director_insulin_deliveries', sa.Column('patient_nombres', sa.String(length=120), nullable=False))
    op.add_column('director_insulin_deliveries', sa.Column('patient_ap_paterno', sa.String(length=80), nullable=False))
    op.add_column('director_insulin_deliveries', sa.Column('patient_ap_materno', sa.String(length=80), nullable=True))
    op.alter_column('director_insulin_deliveries', 'insulin_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('director_insulin_deliveries', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_constraint('director_insulin_deliveries_patient_id_fkey', 'director_insulin_deliveries', type_='foreignkey')
    op.drop_column('director_insulin_deliveries', 'patient_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('director_insulin_deliveries', sa.Column('patient_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('director_insulin_deliveries_patient_id_fkey', 'director_insulin_deliveries', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.alter_column('director_insulin_deliveries', 'quantity',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('director_insulin_deliveries', 'insulin_type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('director_insulin_deliveries', 'patient_ap_materno')
    op.drop_column('director_insulin_deliveries', 'patient_ap_paterno')
    op.drop_column('director_insulin_deliveries', 'patient_nombres')
    # ### end Alembic commands ###