"""add_medical_fields_update

Revision ID: 6e75ca39ed66
Revises: 20260110_000001
Create Date: 2026-01-14 23:34:53.058257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e75ca39ed66'
down_revision = '20260110_000001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complication_types', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('complication_types', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complication_types', 'description')
    op.drop_column('complication_types', 'name')
    # ### end Alembic commands ###