"""agregar_docs_urls

Revision ID: ca352e2b0a60
Revises: 6e75ca39ed66
Create Date: 2026-01-18 03:46:23.291236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca352e2b0a60'
down_revision = '6e75ca39ed66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'deliveries', 'donation_allocations', ['allocation_id'], ['id'], ondelete='CASCADE')
    op.add_column('patients', sa.Column('url_ci_paciente', sa.String(length=500), nullable=True))
    op.add_column('patients', sa.Column('url_certificado_medico', sa.String(length=500), nullable=True))
    op.add_column('patients', sa.Column('url_foto_paciente', sa.String(length=500), nullable=True))
    op.add_column('patients', sa.Column('url_declaracion_aporte', sa.String(length=500), nullable=True))
    op.add_column('patients', sa.Column('url_ci_tutor', sa.String(length=500), nullable=True))
    op.add_column('patients', sa.Column('url_foto_tutor', sa.String(length=500), nullable=True))
    #op.drop_column('patients', 'url_declaracion_jurada')
    #op.drop_column('patients', 'url_compromiso_firmado')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('url_compromiso_firmado', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('url_declaracion_jurada', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('patients', 'url_foto_tutor')
    op.drop_column('patients', 'url_ci_tutor')
    op.drop_column('patients', 'url_declaracion_aporte')
    op.drop_column('patients', 'url_foto_paciente')
    op.drop_column('patients', 'url_certificado_medico')
    op.drop_column('patients', 'url_ci_paciente')
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    # ### end Alembic commands ###